---
- name: Copy PacketLogic
  ansible.builtin.copy:
    src: ./packetlogic2-stats_64-23.20.12.1-lm1.0.9.2-disk1.qcow2
    dest: /usr/local/IDS/packetlogic2-stats_64-23.20.12.1-lm1.0.9.2-disk1.qcow2
    owner: root
    group: root
    mode: '0777'

#- name: Copy PacketLogic
#  ansible.builtin.copy:
#    src: ./insights-storage-v25.20.02-psf.tar.gz.gpg
#    dest: /insights-storage-v25.20.02-psf.tar.gz.gpg
#    owner: root
#    group: root
#    mode: '0777'

#- name: Move Repo Files
#  command:  "qemu-img resize /usr/local/IDS/packetlogic2-stats_64-23.20.12.1-lm1.0.9.2-disk1.qcow2 890G"
#  args:
#    executable: /bin/bash

- name: Sanal makine oluştur
  ansible.builtin.shell: |
    virt-install --connect qemu:///system --name="{{ inventory_hostname.split('.')[-1] }}" \
    --memory="2048" --vcpus="2,sockets=1,cores=2,threads=1" \
    --os-type=linux --os-variant=generic \
    --disk path=/usr/local/IDS/packetlogic2-stats_64-23.20.12.1-lm1.0.9.2-disk1.qcow2,bus=virtio,cache=none \
    --network bridge="ens192",model="virtio" \
    --memorybacking hugepages=on,nosharepages=on,size=1,unit=G \
    --noautoconsole --import --autostart

